services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:5-alpine"
    container_name: "redis"
    ports:
      - "6379:6379"